### ISSUE TITLE
bug: grpc.RpcError: chain errors are expected in JSON format but they are returned as strings.

### ISSUE THREAD

**Issue by onikonychev** [NibiruChain/py-sdk#70]
Regression is coming from this commit: https://github.com/NibiruChain/py-sdk/commit/67745c94fc963223147723ce1fdd1bdca5672ee3#diff-1a2df94eabb4ad224bb6f46a1f2af79b1b236e61f506b118ea8eaa8844084384R112

```py
except grpc.RpcError as err:
      return json.loads(err._state.debug_error_string)["grpc_message"], False
```

Try opening position with insufficient funds:

```
err._state.debug_error_string = 
'UNKNOWN:Error received from peer ipv6:%5B::1%5D:9090 {grpc_message:"failed to execute message; message index: 0: 0unusd is smaller than 10unusd: insufficient funds", grpc_status:2, created_time:"2022-08-15T17:56:51.182382+04:00"}'
```

This is not json and instead of a regular message I'm getting another exception:

```
 JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

@matthiasmatt @Unique-Divine - please take a look. If GRPC errors are expected to be JSON formatted - please fix the chain, otherwise remove parsing json.

**Comment by matthiasmatt** [comment]
Can we hack this? Something like:

```python

def force_json(value: str) -> dict:
    return json.loads(value[value.index("{"):len(value)-value[::-1].index("}")])

```
